### ISSUE TITLE
Not able to connect to SL using adbc driver

### ISSUE THREAD

**Issue by sunkusowmyasree** [dbt-labs/example-semantic-layer-clients#3]
Hi Team,

I am using adbc driver example but not able to connect to dbt semantic layer. PFA for error. Let me know how to resolve this issue?
![image](https://github.com/dbt-labs/example-semantic-layer-clients/assets/10221699/cc4c39a9-9a5f-4ff7-898a-532db2f4bbaf)

**Comment by aiguofer** [comment]
Hi, glad you're trying this out!

From the README:

> This basic example shows how to set up a Python project using hatch to connect to and query the Semantic Layer.
> 
> To run this, make sure you have set the DBT_JDBC_URL env var and run:
> 
> NOTE: Python curlies need to be escaped by doubling them up, so we end up with 4 curlies instead of 2 for the jinja template section.
> 
> `hatch run python src/adbc_example.py 'select * from {{{{ semantic_layer.query(metrics=["orders"]) }}}}'`

This example is written so you will run it from CLI and have the `DBT_JDBC_URL` variable set. It's just an example, so you have to adapt the code to your needs. When you're in a Jupyter notebook, there are no meaningful `sys.args`. This example expects your query to be `args[1]` so you would need to change that to w/e query you're trying to run.

**Comment by il-dat** [comment]
Hi @aiguofer I have an issue connecting SL by using this driver:

My query:
```
python adbc_example.py 'select * from {{ semantic_layer.metrics() }}'
```

Error message:
```
  File "adbc_driver_manager/_lib.pyx", line 1330, in adbc_driver_manager._lib.AdbcStatement.prepare
  File "adbc_driver_manager/_lib.pyx", line 227, in adbc_driver_manager._lib.check_error
adbc_driver_manager.ProgrammingError: INVALID_ARGUMENT: [FlightSQL] Could not establish connection to your SNOWFLAKE data platform: Incorrect username or password was specified. (InvalidArgument; Prepare)
```

I think it is a missing config issue somewhere but the docs is not very helpful to give the direction of fixing it. Do you have any ideas? Thank you so much

**Comment by il-dat** [comment]
> Hi @aiguofer I have an issue connecting SL by using this driver:
> 
> My query:
> 
> ```
> python adbc_example.py 'select * from {{ semantic_layer.metrics() }}'
> ```
> 
> Error message:
> 
> ```
>   File "adbc_driver_manager/_lib.pyx", line 1330, in adbc_driver_manager._lib.AdbcStatement.prepare
>   File "adbc_driver_manager/_lib.pyx", line 227, in adbc_driver_manager._lib.check_error
> adbc_driver_manager.ProgrammingError: INVALID_ARGUMENT: [FlightSQL] Could not establish connection to your SNOWFLAKE data platform: Incorrect username or password was specified. (InvalidArgument; Prepare)
> ```
> 
> I think it is a missing config issue somewhere but the docs is not very helpful to give the direction of fixing it. Do you have any ideas? Thank you so much

Sorry I found it myself, it is the Semantic Crediential config ✅

**Comment by sunkusowmyasree** [comment]
Yes I am able to query semantic metrics from Jupyter. Thanks a lot

**Comment by aiguofer** [comment]
Awesome! glad ya'll both figured it out.

I'm going to push some changes to this example to make it more self-explanatory. Also, you're right @il-dat we need a FAQ for common errors!
